= Общие сведения о сервисе

{cs} является дополнительным модулем {dv}, который обеспечивает возможность конвертации документов между поддерживаемыми форматами с использованием внешнего сервиса конвертации Р7/OnlyOffice. Он предоставляет методы для преобразования файлов в различные форматы, а также содержит вспомогательные методы для работы с URL и настройками сервиса.

Сервис представляет отдельную библиотеку, которая выдаётся по запросу или может быть установлен с помощью инсталлятора. В данный момент в {dv} сервис используется для конвертации файлов из формата Microsoft Word (`.doc`, `.docx`) в PDF-A в примере решения Кадрового Электронного Документооборота (КЭДО). Функциональность и применение модуля не ограничиваются использованием в примере решения.

[NOTE]
====
include::ROOT:partial$exceprts.adoc[tags=license-check]

Также потребуется лицензия на "Р7-Офис. Сервер документов"/OnlyOffice.
====

Пример использования сервиса приведён в https://github.com/Docsvision/WebClient-Samples/tree/master_net45/ServerExtensions/ConversionSample[репозитории примеров {wc}а].

[#purpose-function]
== Назначение и функции модуля

.Сервис позволяет конвертировать файлы между следующими поддерживаемыми форматами: `PDF/A`, `pdf`, `bmp`, `gif`, `jpg`, `odp`, `otp`, `png`, `potm`, `potx`, `ppsm`, `ppsx`, `pptm`, `pptx`, `csv`, `ods`, `ots`, `xlsm`, `xlsx`, `xltm`, `xltx`, `docm`, `docx`, `docxf`, `dotm`, `dotx`, `epub`, `fb2`, `html`, `odt`, `ott`, `rtf`, `txt`.

{cs} принимает на входе файл одного из поддерживаемых форматов и на выходе формирует файл в конвертируемом формате. Подробнее о поддерживаемых преобразованиях см. в разделе "xref:programmer:index.adoc[]".

[#doc-list]
== Разделы документации

.Документация модуля содержит следующие разделы:
. Общие сведения о модуле.
. Администрирование модуля.
. Руководство разработчика {of-cs}.

