= OperationResult -- класс

Универсальный класс, представляющий результат операции. Он включает информацию об успехе или неудаче операции, необязательное сообщение и полезную нагрузку типа `TData`, если это применимо.

* *Пространство имён:* `DocsVision.ConversionService.Services`
* *Сборка:* `DocsVision.ConversionService.dll`

== Синтаксис

[source,csharp]
----
сlass OperationResult<TData>
----

Свойства::
Success:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`
+
Указывает, была ли операция успешной. Если `true`, то операция прошла успешно, если `false`, то операция не удалась.

Message:::
Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`
+
Предоставляет дополнительную информацию об операции. Она может использоваться для передачи подробностей об успехе или неудаче операции.

Data:::
Тип: `TData`
+
Представляет собой полезную нагрузку результата операции. Он содержит фактический результат операции, а его тип определяется универсальным параметром `TData`.
